### ISSUE TITLE
STAT check issue with missing Bold instance

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/axisregistry#104]
There is no Bold instance in this project: https://github.com/dy/wavefont
Theferore we shouldn't expect a Bold instances, nor a linked value to 700 in STAT, and so these 2 FAILS should pass:

* 🔥 **FAIL** Compulsory STAT Axis Values are incorrect:

 | Name | Axis | Current Value | Current Flags | Current LinkedValue | Expected Value | Expected Flags | Expected LinkedValue |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Thin | wght | 100.0 | 0 | None | 100.0 | 0 | None |
| ExtraLight | wght | 200.0 | 0 | None | 200.0 | 0 | None |
| Light | wght | 300.0 | 0 | None | 300.0 | 0 | None |
| Regular | wght | 400.0 | 2 | None | 400.0 | 2 | 700.0 |
 [code: bad-axis-values]

* 🔥 **FAIL** The "wght" axis coordinate of the "Bold" instance must be 700. Got None instead. [code: wght-not-700]

cc @m4rc1e

**Comment by RosaWagner** [comment]
Same with this other project, fontbakery is expecting a `SuperCondensed (25)`, but `min=50`

* 🔥 **FAIL** Compulsory STAT Axis Values are incorrect:

 | Name | Axis | Current Value | Current Flags | Current LinkedValue | Expected Value | Expected Flags | Expected LinkedValue |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Normal | wdth | 100.0 | 2 | None | 100.0 | 2 | None |
| SemiExpanded | wdth | 112.5 | 0 | None | 112.5 | 0 | None |
| Expanded | wdth | 125.0 | 0 | None | 125.0 | 0 | None |
| ExtraExpanded | wdth | 150.0 | 0 | None | 150.0 | 0 | None |
| SuperCondensed | wdth | N/A | N/A | N/A | 25.0 | 0 | None |
| UltraCondensed | wdth | 50.0 | 0 | None | 50.0 | 0 | None |
| ExtraCondensed | wdth | 62.5 | 0 | None | 62.5 | 0 | None |
| Condensed | wdth | 75.0 | 0 | None | 75.0 | 0 | None |
| SemiCondensed | wdth | 87.5 | 0 | None | 87.5 | 0 | None |
| Thin | wght | 100.0 | 0 | None | 100.0 | 0 | None |
| ExtraLight | wght | 200.0 | 0 | None | 200.0 | 0 | None |
| Light | wght | 300.0 | 0 | None | 300.0 | 0 | None |
| Regular | wght | 400.0 | 2 | 700.0 | 400.0 | 2 | 700.0 |
| Medium | wght | 500.0 | 0 | None | 500.0 | 0 | None |
| SemiBold | wght | 600.0 | 0 | None | 600.0 | 0 | None |
| Bold | wght | 700.0 | 0 | None | 700.0 | 0 | None |
| ExtraBold | wght | 800.0 | 0 | None | 800.0 | 0 | None |
| Black | wght | 900.0 | 0 | None | 900.0 | 0 | None |
 [code: bad-axis-values]
</div></details><details><summary>🔥 <b>FAIL:</b> Check hhea.caretSlopeRise and hhea.caretSlopeRun (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/hhea.html#com.google.fonts/check/caret_slope">com.google.fonts/check/caret_slope</a>)</summary><div>

cc @m4rc1e

**Comment by m4rc1e** [comment]
@RosaWagner Which family is causing the SuperCondensed Fail?
