### ISSUE TITLE
Add Vertical Alignment [YALN] axis

### ISSUE THREAD

**Issue by dy** [googlefonts/axisregistry#106]
## Font Project introducing the axis

[Wavefont](https://github.com/dy/wavefont)

## Short description of what the axis does

Aligns bars/glyphs by the baseline, middle line or cap line.

## Image

<img src="https://user-images.githubusercontent.com/300067/208308118-3c94d3d7-802b-4e0b-88aa-f1363626c95c.svg" width="280" />

## Why is the axis needed

From https://github.com/dy/wavefont/issues/37.
Special-case axis that proves to be more useful than having a glyphs range with center-aligned glyphs.
It allows interchange of values between bottom/center/top-aligned view, interchange with [linefont](https://github.com/dy/linefont), keeping spacing/non-marking chars logic unchanged.

## Validate the incoming custom axis against the Axis Registry

The Slant `slnt` axis can be dovetailed for the purpose of alignment, for it has units range _-90-90_ resembling phase plot:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/300067/208307629-a67693cc-fea6-499c-823b-c64e72c1c52c.png">  
But that's not directly the meaning of alignment.
Should `slnt` be used as exception for wavefont?

## Axis metadata fields (updated)

```
#YALN based on [Wavefont](https://github.com/dy/wavefont)
tag: "YALN"
display_name: "Y Alignment"
min_value: -100
default_value: 0 
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
# fallback {
#   name: "Bottom"
#   value: -100
# }
# fallback {
#   name: "Top"
#   value: 100
# }
fallback_only: false
description: "Align glyphs from their default position (usually the baseline) to a lower or upper bound."
````

**Comment by m4rc1e** [comment]
Wavefront is now using the Round axis (ROND). Has this proposal been abandoned?

**Comment by dy** [comment]
By _this_ you mean ALGN? 
Afaik ROND proposal was merged. Wavefont still uses ALGN, but waiting for googlefonts to make a decision if ALGN should be merged or I can refactor wavefont to use slnt instead @davelab6 @RosaWagner

**Comment by davelab6** [comment]
Thanks @dy! 

The GF team is reviewing the incoming axis proposals in batches, ordered roughly according to when they were proposed (FIFO), but also with priorities determined by the senior engineering team.

I don't think using slant is good, I think we can see about getting a vertical alignment axis added to the next batch.

I like your range proposal going negative and positive, and I think a percent style range (100s, no decimals) is easier semantics. Something like this:

```
#VALN based on [Wavefont](https://github.com/dy/wavefont)
tag: "VALN"
display_name: "Vertical Alignment"
min_value: -100
default_value: 0 
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
# fallback {
#   name: "Bottom"
#   value: -100
# }
# fallback {
#   name: "Top"
#   value: 100
# }
fallback_only: false
description: "Align glyphs from their default position (usually the baseline) to a lower or upper bound."
````

**Comment by vv-monsalve** [comment]
@dy You would like to read the [Axis Registry Protocol](https://googlefonts.github.io/gf-guide/axis-registry.html) article in the GF-Guide, providing detailed information for the inclusion of a new axis, the Axis Requirements, and the Type of Axes, which could lead to a revision of the proposed values.

@davelab6 
> tag: "VALN"
display_name: "Vertical Alignment"

Vertical better than `XALGN` _alignement in x_ in this case?

**Comment by davelab6** [comment]
Well i would be Y, but yes, worth considering! :)

**Comment by vv-monsalve** [comment]
> Well it would be Y, but yes, worth considering! :)

Ups, yes, Y in this case. We have been using X and Y notation, so indeed worth considering out of consistency :]

**Comment by vv-monsalve** [comment]
Also, only the `Default` fallback position should be included in the registry. We are no longer included per axis registry. The suggested/commented fallbacks above should be considered to be added only to the family (if needed).

**Comment by dy** [comment]
Ok, I can refactor wavefont then to `YALN`

**Comment by chrissimpkins** [comment]
We'll open the axis registration PR for the final round of discussion on it.

**Comment by vv-monsalve** [comment]
Tag: `YELA`
Display name: `Vertical Element Alignment`

**Comment by dy** [comment]
@vv-monsalve so will it be changed to `YELA`? Should I refactor wavefont to `YELA`?

**Comment by vv-monsalve** [comment]
@dy Yes please, I'll update de axis registry.

**Comment by dy** [comment]
Ok, done.
