### ISSUE TITLE
Add Horizontal Position Paint 1 [XPN1] axis

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/axisregistry#113]
## Font Project introducing the axis

Bitcount (still a private project)

## Short description of what the axis does

The position of the background color moves left and right. The negative values move to the left and positive values to the right, in the X dimension.

## Image

![COLX](https://user-images.githubusercontent.com/48698976/226986580-b28c31d6-3aac-486b-aeed-c1dbc76e14d2.gif)

## Why is the axis needed

The font experiments with generating a "background drawing" that is shifted and scaled using the shape pixels as masks. There is currently working on a version where that background contains a number of color shapes. With an 'x' and 'y' position axes the layers of color shapes can be moved/selected behind the glyph pixel masks.

## Axis metadata fields

```
# COLX based on a still private project
tag: "COLX"
display_name: "Color Position in X"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "The position of the background color moves left and right. "
  " Negative values to the left and positive values to the right, "
  " in the X dimension."
````

**Comment by vv-monsalve** [comment]
There is another [axis proposing "vertical"](https://github.com/googlefonts/axisregistry/issues/106) instead of Y.  However, the proposed name for this axis was kept as follows the 'X-Y' notation we've used so far for position or behavior described from cartesian planes.

**Comment by vv-monsalve** [comment]
The font introducing this axis would need to use duplicated instances of `COLX` and `COLY` to control the position of two different layers. Layer1 = (CLX1, CLY1) and layer2 = (CLX2, CLY2)

![Screen_Recording_2023-03-16_at_18_18_47_AdobeExpress-2](https://user-images.githubusercontent.com/48698976/225776962-4709775d-5c57-4620-a3e8-0de3da8c47a3.gif)

**Comment by vv-monsalve** [comment]
```
# XLY1 based on a still private project
tag: "XLY1"
display_name: "Layer 1 position in X"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "The position of the background color moves left and right. "
  " Negative values to the left and positive values to the right, "
  " in the X dimension."
````

**Comment by vv-monsalve** [comment]
In relation to the [comment made in "LYSZ"](https://github.com/googlefonts/axisregistry/issues/117#issuecomment-1652606877), should this axis better be `Horizontal Position Paint 1"

**Comment by vv-monsalve** [comment]
Last axis definition revision


#### **`XPN1`**

```
# XPN1 based on a still private project
tag: "XPN1"
display_name: "Horizontal Position Paint 1"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "The position of the paint moves left and right. Negative values"
  " to the left and positive values to the right, in the X dimension."
  " Paint 1 is behind Paint 2."
````

#### **`XPN2`**

```
# XPN2 based on a still private project
tag: "XPN2"
display_name: "Horizontal Position Paint 2"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "The position of the paint moves left and right. Negative values"
  " to the left and positive values to the right, in the X dimension."
  " Paint 2 is in front of Paint 1."
````

**Comment by davelab6** [comment]
I made small tweaks - great stuff - ship it :)
