### ISSUE TITLE
Add Size of Paint 1 [SZP1] axis

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/axisregistry#117]
## Font Project introducing the axis

Bitcount (still a private project)

## Short description of what the axis does

Modifies the size of the background color. It goes from an initial size (0) to negative values to shrink down (-100%) the size or positive values to increase it (100%).

## Image

![CLSZ](https://user-images.githubusercontent.com/48698976/226971917-68fc215d-1e11-435f-885a-d9bdb9a2144c.gif)

## Axis metadata fields

```
#COSZ based on a still private project
tag: "COSZ"
display_name: "Color Size"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: 
  "Modifies the size of the background color. It goes from"
  " an initial size (0) to negative values to shrink down (-100%) the size"
  " or positive values to increase it (100%)."
````

**Comment by vv-monsalve** [comment]
The proposed name and tag for this axis were changed to `Color Size` to make it more general purpose (not only gradient color element could increase the size) and also to follow the Protocol's guideline for a two words axis name, but also given there is already SZ convention for size (from `opsz`). However, given there would be COLX, and COLY, should this one be COLS?

**Comment by rsheeter** [comment]
The size of color is a confusing concept imho, is there some other way to describe this? The size of the backdrop element say?

**Comment by vv-monsalve** [comment]
Fair question. In that case, perhaps we should find a better word to describe all of the "COLOR" related axes. Backdrop or background, or any other word that could work to depict the elements that behave as _fillers_.

**Comment by vv-monsalve** [comment]
Notation revision gains relevance concerning the associated axes (COLX, COLY) introduced by this project. As well as a technical revision when the axis implementation requires [duplication](https://github.com/googlefonts/axisregistry/issues/113#issuecomment-1472906749).

**Comment by vv-monsalve** [comment]
Taking the above (link) as a reference, we could use the concept of Layer instead of Color to refer to elements that could be moved or magnified, making it a broader concept. 

````
#LYSZ based on a still private project
tag: "LYSZ"
display_name: "Layer Size"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: 
  "Modifies the size of a layer element going from."
  " an initial size (0) to negative values to shrink down (-100%) the size"
  " or positive values to increase it (100%)."
````

**Comment by vv-monsalve** [comment]
Reconsidering all the 'Color' related axes name schema, would "Paint" instead of "Layer" be more suitable for color elements, e.g. `Paint Size`?. Indeed, the Paints could be piled up in a layered system, but Paint is the actual "object" arranged in layers. 
Additionally, as a concept, it communicates a color-related meaning to users and will be related to the format semantics.

**Comment by vv-monsalve** [comment]
Last axis definition revision


#### **`SZP1`**

````
#SZP1 based on a still private project
tag: "SZP1"
display_name: "Size of Paint 1"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: 
  "Modifies the size of a paint element going from an initial size (0)"
  " to negative values to shrink down the size (-100%)"
  " or positive values to increase it (100%)."
  " Paint 2 is in front of Paint 1."
````

#### **`SZP2`**

````
#SZP2 based on a still private project
tag: "SZP2"
display_name: "Size of Paint 2"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: 
  "Modifies the size of a paint element going from an initial size (0)"
  " to negative values to shrink down the size (-100%)"
  " or positive values to increase it (100%)."
  " Paint 2 is in front of Paint 1."
````

**Comment by davelab6** [comment]
@rsheeter where @vv-monsalve said "Last axis definition revision", this refers to these axes names/values/descriptions being approved by @evanwadams in our review meeting. Please could you also confirm these axis registry definitions look good?

**Comment by davelab6** [comment]
@rsheeter and I chatted and this is good to go with one small change. Rod asked "what is a paint 1" which is a reasonable question, so to make the display name (a bit =) more self explanatory, I propose to change

    display_name: "Size of Paint 1"

to

display_name: "Size of Paint, 1"

and

    display_name: "Size of Paint 2"

to

    display_name: "Size of Paint, 2"

**Comment by vv-monsalve** [comment]
The numbers are intended to act as an identifier of the Paints, so they are indeed related to each Paint. There would be a `Paint 1`, a `Paint 2` and each of them in turn will have Positions in X and Y dimensions (XPN1, XPN2).

When we say, '`Paint 2 is in front of Paint 1` in the description, we are using them as "names" or identifiers.

Adding the comma here would disassociate the index from the Pain and would make it related to a size instead, which could be even more confusing.

**Comment by davelab6** [comment]
Okay yes you are right, disregard this suggestion and proceed :D
