### ISSUE TITLE
List which new axes these proposed new VF families have

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/axisregistry#13]
There are a few open issues at google/fonts to add some VF families that have axes supposedly not yet specified in the GFAxisRegistry.

This is an umbrella issue to take some time to inspect these projects and open individual "Add Axis" issues.

- [x] https://github.com/google/fonts/issues/3883
- [x] https://github.com/google/fonts/issues/3802
- [x] https://github.com/google/fonts/issues/3115

**Comment by vv-monsalve** [comment]
Kablammo Issues is [#9](https://github.com/googlefonts/axisregistry/issues/9)

**Comment by chrissimpkins** [comment]
Tilt requires rotation horizontal and rotation vertical
