### ISSUE TITLE
Add Shadow Rotation [SHDR] axis

### ISSUE THREAD

**Issue by yanone** [googlefonts/axisregistry#147]
No upcoming font in Google Fonts currently needs this, but choosing rotation of shadows is a common feature that will be requested sooner or later.

This axis complements the previous SHDW proposal (https://github.com/googlefonts/axisregistry/issues/122)

```
# SHDR
tag: "SHDR"
display_name: "Shadow Rotation"
min_value: -180
default_value: 0
max_value: 180
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description: "Adjust the rotation angle of a shadowed font. A shadow rotation of 0 points straight downwards. Positive values rotate counter-clockwise, negative values rotate clockwise."
```

**Comment by yanone** [comment]
Could also be SHRO actually. SHDR completes to _shader_ in my head.

**Comment by vv-monsalve** [comment]
Per the Axis Registry Protocol, we are not registering speculative axis. "There should be a production-ready VF project with the new axis. Axes can’t be defined up front without a variable font family that requires the axis." https://googlefonts.github.io/gf-guide/axis-registry.html#an-existing-font-project-introducing-the-axis
