### ISSUE TITLE
Add Style [STYL] axis

### ISSUE THREAD

**Issue by yanone** [googlefonts/axisregistry#148]
### Font project(s) using the axis

https://github.com/EkType/Honk

### Short description of what the axis does

The font changes its appearance (style) multiple times on on the STYL axis.

### Image

![honk](https://github.com/googlefonts/axisregistry/assets/175386/1027197d-edf1-4da7-a310-bced8d3cdc3a)
_Please note that the shadow that extends under the glyphs in the second half of the animation is not part of the STYL axis. This comes as part of the SHDW axis._

### Why is the axis needed

It's a bit difficult for me to write a case for it other than me finding it legitimate to change the font style along an axis. Sorry. Ektype has made a cool thing.

### Axis metadata fields

```
#STYL based on https://github.com/EkType/Honk
tag: "STYL"
display_name: "Style"
min_value: 0
default_value: 0
max_value: 100
precision: -1
fallback {
  name: "Default"
  value: 0.00
}
fallback_only: false
description: "Changes font style up to several times along one axis."
```

**Comment by vv-monsalve** [comment]
`MORF` axis could be used for this purpose.

**Comment by davelab6** [comment]
Agreed, morph is this kind of change without making a different style, kind of variation.
