### ISSUE TITLE
Add Element Shape (ELSH) Axis

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/axisregistry#15]
* **Description:** "Controls the shape of the element"
* **Range:** 0.0 - 16.0

Fonts to be onboarded that have this axis:
* https://github.com/google/fonts/issues/3817

**Comment by davelab6** [comment]
Per discussion with Evan and others, we want to define this as 0.0..100.0 to allow for future fonts with more shapes

**Comment by vv-monsalve** [comment]
## Element Shape

```
#Element Shape, based on https://github.com/rosettatype/handjet
tag: "ESHP" 
display_name: "Element Shape"
min_value: 0.0
default_value: 0.0
max_value: 100.0
precision: -1
description: 
    "Controls the shape of the element"
```
![Handjet-ESHP-animation_word](https://user-images.githubusercontent.com/48698976/181379986-bc74c71c-a301-4563-9815-f3ab22a37391.gif)

**Comment by davelab6** [comment]
Agreed -1 precision is good

**Comment by chrissimpkins** [comment]
Axis tag will be changed to ELSP

**Comment by RosaWagner** [comment]
Evan and Dave confirmed ELSH and ELGR
