### ISSUE TITLE
Add Horizontal Element Alignment [XELA] axis

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/axisregistry#157]
### Requirements

- [x] I have inspected the current [Axis Registry](https://github.com/googlefonts/axisregistry/tree/main/Lib/axisregistry/data) and there is not a registered custom axis that could be used for the variation purpose on the upcoming font project.
- [x] The metadata fields of the proposed axis meet the *Axis Requirements* as specified in the Protocol (linked above).

### Font project(s) using the axis

SixtyFour Color (to be renamed) at https://github.com/jenskutilek/homecomputer-fonts

### Short description of what the axis does

As a parallel to Vertical Element Alignment [YELA], this controls the position of horizontal elements.

### Image

![xela](https://github.com/googlefonts/axisregistry/assets/106728/1120af37-392b-4886-8abd-909d53328484)

### Why is the axis needed

As the counterpart to YELA.

### Axis metadata fields

(Remove this line and fill out the mock of the data structure of the axis)

```
#YELA based on [Wavefont](https://github.com/dy/wavefont)
tag: "XELA"
display_name: "Horizontal Element Alignment"
min_value: -100
default_value: 0
max_value: 100
precision: 0
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "Align glyphs from their default position (0%),"
  " usually the baseline, to a rightmost (100%)"
  " or leftmost (-100%) position."

````

**Comment by vv-monsalve** [comment]
Could this be the same `XALN` #126?

**Comment by vv-monsalve** [comment]
Revised description would be
````
description:
  "Align glyph elements from their default position (0%),"
  " usually the baseline, to a rightmost (100%)"
  " or leftmost (-100%) position."
````

**Comment by vv-monsalve** [comment]
Revised definitions on January 26:

> Precision value could be -1 to allow the fine control and 1000 positions

````
#XELA based on [Sixtyfour Convergence](https://github.com/jenskutilek/homecomputer-fonts/tree/master/Sixtyfour)
tag: "XELA"
display_name: "Horizontal Element Alignment"
min_value: -100.0
default_value: 0
max_value: 100.0
precision: -1
fallback {
  name: "Default"
  value: 0
}
fallback_only: false
description:
  "Align glyph elements from their default position (0%),"
  " usually the baseline, to a rightmost (100%)"
  " or leftmost (-100%) position."
````
