### ISSUE TITLE
Add Element Grid (EGRD) Axis

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/axisregistry#16]
* **Description:** "Controls how many elements are used per one grid unit"
* **Range:** 1.0 - 2.0

Fonts to be onboarded that have this axis:
* https://github.com/google/fonts/issues/3817

**Comment by vv-monsalve** [comment]
## Element Grid

```
#Element Grid, based on https://github.com/rosettatype/handjet
tag: "EGRD" 
display_name: "Element Grid"
min_value: 1.0
default_value: 2.0
max_value: 1.0
precision: -1
description: 
    "Controls how many elements are used per one grid unit."
```
![Handjet-EGRD-animation](https://user-images.githubusercontent.com/48698976/181381818-f95bfc80-4e5f-4752-9851-793a7d1ae553.gif)
