### ISSUE TITLE
`SLNT` and `ITAL` docs needs to be more clear about direction of slant

### ISSUE THREAD

**Issue by tphinney** [googlefonts/axisregistry#161]
**Describe the issue**
A typical right-leaning slant is _negative_, which is the reverse of the “average person’s” expectation. That is, a typical right-leaning slant might be -10°. This is not at all explicit in the docs, and _it really should be_.

I realize these are axes in the regular OpenType axis registry, which is very explicit about this issue. But if Google is going to duplicate them, it should be equally clear.

**Comment by vv-monsalve** [comment]
>  This is not at all explicit in the docs, and it really should be.

Could you please clarify to which documents you are referring?

**Comment by tphinney** [comment]
Actually, ITAL is binary and just 0 or 1, so it is obvious that 1 is “on”

BUT SLNT is -90 to 90, and the Google "description" at https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/slant.textproto does not include the critical interpretation info that the Microsoft version of the axis registry has: “Values can be interpreted as _the angle, in counter-clockwise degrees_, of oblique slant from whatever the designer considers to be upright for that font design” (emphasis added) AND later in additional information “Note that the scale for the Slant axis is interpreted as the angle of slant in counter-clockwise degrees from upright. This means that a typical, right-leaning oblique design will have a negative slant value. This matches the scale used for the italicAngle field in the ['post'](https://learn.microsoft.com/en-us/typography/opentype/spec/post) table.”

**Comment by vv-monsalve** [comment]
The axis description in the `textproto` file is intended for font users when interacting with them in the `Type tester` tab of the Specimen page of the font. It would appear in the `i` tooltip next to the axis name. 

<img width="434" alt="Screenshot 2024-08-08 at 12 21 35" src="https://github.com/user-attachments/assets/e1971a56-e52e-4162-a6b2-edb91b97fee3">

For this particular case, where we have spotted that this critical interpretation is challenging even for font developers, I wonder if mentioning it here could bring more confusion than clarity. However, I'm drafting here a revision proposal:

#### Current description 

```
  "Adjust the style from upright to slanted, also known to typographers"
  " as an 'oblique' style. Rarely, slant can work in the other direction,"
  " called a 'backslanted' or 'reverse oblique' style."
```

#### Description proposal

```
  "Adjust the style from upright to slanted. Negative values would produce"
  " right-leaned forms, also known to typographers as an 'oblique' style."
  " Positive values would produce left-leaned forms, also called a 'backslanted'"
  " or 'reverse oblique' style."
```

**Comment by tphinney** [comment]
Nice! That is a good direction for an adjusted description.

I would suggest deleting the word “would” (in two places), and change “-leaned” to “-leaning” (also twice).

**Comment by vv-monsalve** [comment]
Ty, @tphinney! I've updated the proposal now with the feedback. We'll review this in our next Axis Registry meeting ;-)

**Comment by davelab6** [comment]
@evanwadams approved this copy update
