### ISSUE TITLE
Add Flair Axis

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/axisregistry#20]
Fonts to be onboarded that have this axis:
* https://github.com/google/fonts/issues/3124

**Comment by davelab6** [comment]
https://github.com/googlefonts/axisregistry/commit/a3e79752d4fdac7bae5d9b4903d85247c89f9c2f added https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/flair.textproto and now it needs an illustration from @elliotjaystocks
