### ISSUE TITLE
Add Volume (VOLM) Axis

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/axisregistry#21]
Fonts to be onboarded that have this axis:
* https://github.com/google/fonts/issues/3124

**Comment by RosaWagner** [comment]
Current proposal:

```
tag: "VOLM"
display_name: "Volume"
min_value: 0.0
default_value: 0.0
max_value: 100.0
precision: -2
fallback {
  name: "Default"
  value: 0.0
}
description: "The volume axis works only in combination with the Flair axis. It transforms the glyphic serifs to wedge-like ones and add a little more edge to details."
```

**Comment by vv-monsalve** [comment]
The description of the axis is too targeted at the font introducing the axis. From the rest of the axis definition (name, type of axis, and range), `VOLM` could be used separately from Flair in another font, so the description should leave that option open

**Comment by RosaWagner** [comment]
Yes I completely agree, I am hoping @davelab6 finds a good description :)
