### ISSUE TITLE
Add Informality (INFM) axis

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/axisregistry#37]
Related to Issue https://github.com/googlefonts/axisregistry/issues/38

## Description

The in-progress OFL [Shantell Sans](https://shantell-sans.arrowtype.com) is a marker-style font that has an _Irregularity_ axis `IRGL` that goes from **normalized shaping** (letters conform to baseline, x-height, etc, like a normal font) to **irregular shaping** (some letters are smaller or larger than others, or have odd proportions in other ways, more like quick handwriting).

![image](https://user-images.githubusercontent.com/45946693/166855539-2814f03f-c694-41e0-8a23-9ae594ee1cb2.png)

## Range

- Min: `0` (the most normalized expression of a given typeface)
- Max: `100` ( the most organic/irregular expression of a given typeface)

## Instances

- **Normal** – `IRGL: 0` – Maybe an elided name, except in static subfamilies, to differentiate from full variable font family name
- **Irregular**  – `IRGL: 100`

It can be very important to have instances between `0` and `100`, especially if the Irregular style is quite irregular, and you wish to typeset longer passages of text but with a hint of handwritten feeling. In a font, a little irregularity can go a long way!

## Question

What might intermediate instances be named, e.g. at `IRGL 50`? _Semiregular?_ _Seminormal?_ Or, should this be _Irregular_, and the `IRGL 100` be something like _ExtraIrregular_?

With a lot of these names, I do somewhat worry that there may be confusion between this and other style descriptors. For instance, _Semiregular_ sounds a lot like a nonsensical weight name – like _SemiBold_ but for _Regular_. It’s less of a problem, but I also wonder if it’s an issue that _Normal_ is a value in the CSS property `font-style` (the opposite of `Italic`). 

Any thoughts or suggestions appreciated!

**Comment by arrowtype** [comment]
What might be my next steps be here? Hoping to get these fonts finished and onboarded in the coming month or two. Thanks!

**Comment by arrowtype** [comment]
Do we need to complete this issue before I can successfully master a font for Google Fonts, using this axis?

**Comment by arrowtype** [comment]
> What might intermediate instances be named, e.g. at IRGL 50? Semiregular? Seminormal? Or, should this be Irregular, and the IRGL 100 be something like ExtraIrregular?

With a bit more time to think about this, my current thoughts are that the best approach might be:

- `IRGL 0` is labeled _Normal_ or _Normalized_
- `IRGL 50` is labeled _Irregularish_ — This is pretty informal for a style name, but using "Semirregular" is just too confusing due to weight names SemiBold and Regular.
- `IRGL 100` is labeled _Irregular_

**Comment by davelab6** [comment]
Overall, @vv-monsalve suggested that [fonts.google.com/knowledge/glossary/casual_axis](https://fonts.google.com/knowledge/glossary/casual_axis) might work well for this, as it seems to fit the definition provided there. That works both like a percentage range and as a boolean: `0.00..1.00`

**Comment by davelab6** [comment]
@vv-monsalve and I have been discussing if there really is any meaningful difference between `0.00..1.00` and `0..100`.... True boolean values are binary values, `0..1` with no steps, and while `0.00..1.00` has a min/max that without the decimal become boolean, 0% and 100% are also immediately understood as off/on. 

So if we do have a new axis name, I think `0..100` is good.... if this belongs to the existing name, then we will have to accept the previous range `0.00..1.00`, but we could add new intermediate named styles (on a per family basis).

**Comment by arrowtype** [comment]
Nice, yeah I totally agree with that. I do think that most people are generally more used to thinking of things as partial percentages, e.g. `50%`, than they are as decimals, e.g. `0.5`. Battery levels on phones & laptops, progress toward a goal, level of power output in terms of effort (“I’m giving this exercise 100%!”), etc. It’s harder to think of non-technical things that have a range expressed in 0.0 to 1.0...

But yes, 0.0 to 0.1 still allows 0.5. In the future, I could imagine adding a “SemiCasual” instance to Recursive, as some people really seem to prefer this style to either end of the scale. But, for an axis that I specifically intend to be used as a range, 0–100 is appealing in that it seems to suggest a range from the beginning.

**Comment by vv-monsalve** [comment]
Completed in #90
