### ISSUE TITLE
Fallback for wght=1 and wght=1000?

### ISSUE THREAD

**Issue by yanone** [googlefonts/axisregistry#40]
Cairo has an ExtraBlack weight. The `wght` definition here seems contradictory on this as it allows 1 and 1000 but doesn’t define fallbacks for those values. Shall we add them?

**Comment by RosaWagner** [comment]
For now we have been allowing them in FVAR ans STAT, but GF still doesn't support them I think for rendering issues

**Comment by RosaWagner** [comment]
Wille add it to the the pipeline meeting subjects, cause at least 1000 could be supported imo.

**Comment by vv-monsalve** [comment]
> For now we have been allowing them in FVAR ans STAT, but GF still doesn't support them I think for rendering issues

Allowing them both wght= 1 - HairLine and wght=100 - ExtraBlack in the `fvar` table also?

Otoh, I would advocate for:

```
fallback {
  name: "HairLine"
  value: 1
}
fallback {
  name: "ExtraBlack"
  value: 1000
}
```

So the users receive the static instances. This would be particularly helpful for projects such as Sofia Sans.

cc @davelab6

**Comment by yanone** [comment]
+1

**Comment by m4rc1e** [comment]
Nunito Sans also needs ExtraBlack, https://github.com/googlefonts/NunitoSans/pull/14

**Comment by davelab6** [comment]
No, we won't add them, because fall backs is about legacy system support, and legacy systems only support the 100 to 900 weights.
