### ISSUE TITLE
Add Horizontal and Vertical Rotation axes (HROT and VROT)

### ISSUE THREAD

**Issue by yanone** [googlefonts/axisregistry#41]
The names are probably up for discussion, but [Tilt](https://github.com/andyclymer/Tilt-Typeface) has these two axes `HROT` and `VROT` that we need to somehow support. See the animated images in its repo for clarification.

**Comment by yanone** [comment]
Because it's a rotation, I propose values to go from `-180` to `+180` for any rotational axes

**Comment by vv-monsalve** [comment]
## Vertical Rotation

```
#Vertical Rotation, base on https://github.com/andyclymer/Tilt-Typeface
tag: "VROT" 
display_name: "Vertical Rotation"
min_value: -180
default_value: 0.0
max_value: 180
precision: 0
description: 
    " "
```

## Horizontal Rotation

```
#Horizontal Rotation, base on https://github.com/andyclymer/Tilt-Typeface
tag: "HROT" 
display_name: "Horizontal Rotation"
min_value: -180
default_value: 0.0
max_value: 180
precision: 0
description: 
    " "
```
![Big-Neon-Abc](https://user-images.githubusercontent.com/48698976/169555894-2a0e991b-d890-4029-8dd2-e123748b97d9.gif)
![Big-Prism-Abc](https://user-images.githubusercontent.com/48698976/169555906-e1e8beb9-ab58-46b8-8503-40716e8e58c6.gif)
![Big-Warp-Abc](https://user-images.githubusercontent.com/48698976/169555916-12e339e9-ae51-446a-acae-c1ddc38e412e.gif)

**Comment by vv-monsalve** [comment]
Hi @yanone, please check if the information above is ok for the axes and edit (e.g. adding the description) anything.

I don't remember right now which were the optional names we discussed at one point in the meeting, but I can remember we said this is not an actual rotation as it happens in a more 3D way. Perhaps it was ZRotation?

**Comment by davelab6** [comment]
if `precision: 0` then `default_value: 0.0` should be `default_value: 0` since precision 0 means no values after the decimal place; `-1` means one digit after, etc. 

Possibly these 2 should be `Rotation, Horizontal` with tag `ROTH` and `Rotation, Vertical` with tag `ROTV` so that they sort together in alphabetical sorts. 

Also perhaps X and Y instead of Horizontal and Vertical.

**Comment by vv-monsalve** [comment]
> if `precision: 0` then `default_value: 0.0` should be `default_value: 0` since precision 0 means no values after the decimal place; `-1` means one digit after, etc.

Right, I copied the list from another case and forgot to change it. Updated now.

> Also perhaps X and Y instead of Horizontal and Vertical.

I don't know how descriptive or user-friendly would X and Y be. It could be one of the following:

    Z Rotation Horizontal -> ZROTH` +  Z Rotation Vertical -> ZROTV

    Z Rotation X -> ZROTX + Z Rotation Y -> ZROTY

`Z` as it's a rotation in that axis.

**Common rotation**
<img width="370" alt="Screen Shot 2022-05-20 at 11 28 01" src="https://user-images.githubusercontent.com/48698976/169573896-b749e652-f303-427a-8251-396189263d30.png">

**Tilt Rotation Horizontal**
<img width="316" alt="Screen Shot 2022-05-20 at 11 28 07" src="https://user-images.githubusercontent.com/48698976/169573945-d8b2b716-ca18-4957-874d-b3e26cb25a77.png">

**Tilt Rotation Vertical**
<img width="369" alt="Screen Shot 2022-05-20 at 11 43 13" src="https://user-images.githubusercontent.com/48698976/169574166-00d7a61a-b8b8-4b47-8f0a-1acc2a593e55.png">

**Comment by vv-monsalve** [comment]
> This would mean Tilt rotates around the x and z axis.

Right, it would be on the x and z axes.

> Horizontal and vertical, in comparison, sounds very straightforward to comprehend

Agree, that was my concern around user-friendly names. 
Although I'm still unsure if by calling all of them Rotation, how easy would it be to differentiate the three axes' behavior. Revolve? `Revolve Horizontal (REVH)`

**Comment by yanone** [comment]
Revolution is defined as an object that revolves at a distance around another point or object, and it's not clear whether it also rotates. Rotation happens in place and without distance to the middle point. Revolution is misleading.

**Comment by vv-monsalve** [comment]
I was thinking on [Revolve](https://www.oxfordlearnersdictionaries.com/us/definition/english/revolve?q=revolve) not revolution. Unless either my English falls short here or it is not a too common word in English.

**Comment by vv-monsalve** [comment]
Considering:

> I don't know which approach is better. Horizontal and vertical, in comparison, sounds very straightforward to comprehend, but we should consider the third axis from the beginning. Things _will_ rotate around the third axis and even if it's a font that has only this third (common) type of rotation, which could also simply be called Rotation.

> Possibly these 2 should be Rotation, Horizontal with tag ROTH and Rotation, Vertical with tag ROTV so that they sort together in alphabetical sorts.

I'm updating the H-V proposal as follows, leaving the open space for `z` to be just called `ROTA`:

## Rotation Vertical

```
#Vertical Rotation, based on https://github.com/andyclymer/Tilt-Typeface
tag: "ROTV" 
display_name: "Rotation Vertical"
min_value: -180
default_value: 0
max_value: 180
precision: 0
description: 
    "Letters rotate around the y axis"
```

## Rotation Horizontal

```
#Horizontal Rotation, based on https://github.com/andyclymer/Tilt-Typeface
tag: "ROTH" 
display_name: "Rotation Horizontal"
min_value: -180
default_value: 0
max_value: 180
precision: 0
description: 
    "Letters rotate around the x axis"
```

## Rotation

```
#Rotation
tag: "ROTA" 
display_name: "Rotation"
min_value: -180
default_value: 0
max_value: 180
precision: 0
description: 
    "Letters rotate around the z axis"
```

**Comment by davelab6** [comment]
> Possibly these 2 should be `Rotation, Horizontal` with tag `ROTH` and `Rotation, Vertical` with tag `ROTV` so that they sort together in alphabetical sorts.
> 
> Also perhaps X and Y instead of Horizontal and Vertical.

I spoke to Evan about this and he had a strong preference for X and Y over H and V, since we already have parametric axes with X and Y, and while these are not Font Bureau Parametric Axes, they are focused on isolated changes in X or in Y dimensions, so he prefers not to introduce a new second term for the same thing.

He also required XROT and YROT but the labels could sort the same, like "Rotate in X" and "Rotate in Y". (Vertical and Horizontal are also long and we have a preference for short labels)

**Comment by vv-monsalve** [comment]
> I spoke to Evan about this and he had a strong preference for X and Y over H and V

Okay, thanks for the clarification, wasn't aware of this. In that case, it would be:

## Y Rotation

```
#Rotation in Y, based on https://github.com/andyclymer/Tilt-Typeface
tag: "YROT" 
display_name: "Rotation in Y"
min_value: -180
default_value: 0
max_value: 180
precision: 0
description: 
    "Letters rotate around the Y axis"
```

## X Horizontal

```
#Rotation in X, based on https://github.com/andyclymer/Tilt-Typeface
tag: "XROT" 
display_name: "Rotation in X"
min_value: -180
default_value: 0
max_value: 180
precision: 0
description: 
    "Letters rotate around the X axis"
```

**Comment by davelab6** [comment]
Perfecto
