### ISSUE TITLE
Add Terminal Shape (TSHP) axis

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/axisregistry#43]
This new custom axis is included in [Geologisk](https://github.com/monokromskriftforlag/geologisk#variable-axis) to modify the top terminals of stems.

----
Originally posted and discussed at https://github.com/google/fonts/issues/2849

----

![100890763-98473e80-3486-11eb-89f7-c169eca4b0e2](https://user-images.githubusercontent.com/48698976/169421734-9014fc7a-4add-4845-b4c3-25bf0c95fb62.gif)

```
#TSHP based on https://github.com/monokromskriftforlag/geologisk/#variable-axis
tag: "TSHP"
display_name: "Terminal shape"
min_value: 0.00
default_value: 0.00
max_value: 2.00
precision: -2
fallback {
  name: "Plain"
  value: 0.00
}
fallback {
  name: "Pointy" (or "Spiky")
  value: 1.00
}
fallback {
  name: "Rounded"
  value: 2.00
}
description: "Adjust the shape of the stem terminals."
```

**Comment by vv-monsalve** [comment]
This issue was transferred to https://github.com/googlefonts/axisregistry/issues/43. Please follow up there.

**Comment by davelab6** [comment]
Maybe order could change to:

```

fallback {
  name: "Pointy" (or "Spiky")
  value: -100.00
}
fallback {
  name: "Plain"
  value: 0.00
}
fallback {
  name: "Rounded"
  value: 100.00
}

**Comment by dberlow** [comment]
Are the intermediates of this axis useful?

**Comment by vv-monsalve** [comment]
Reviewing this again, probably the range would be better from -100 to 100 (no decimals) indeed.

**Comment by davelab6** [comment]
> Are the intermediates of this axis useful?

Yes for animation

> Is this what you intend to define rounded terminal axis with?

We are considering the pros and cons of 2 axes for rounding terminals and for sharpening terminals vs 1 axis

**Comment by vv-monsalve** [comment]
Summarizing comments from different related conversations on the need to find a better name for the axis:

Overview:
- At least one font has been identified for each of the three cases that could support this axis:
  Using the negative subrange (0 -100) to make Sharp or Pointy shapes -  a `Sharp` axis was originally asked for this.
  Using the positive subrange (0 -100) to make round shapes - a `Rond` axis is required for this
  Using the entire range to go from one extreme to the other, from Sharp to Rounded, going through a neutral state (Flat, plain, default). - This is why the original Sharp evolved to the currently called `Terminal Shape`.
- The first two names, `Sharp` or `Round` for an axis covering the whole range, would bring a semantic conflict when there is only one sub-range used since the axis name would mean the opposite. The above first case being defined from `ROND` wouldn't make much sense. This has already been the case for not using the `Soft` axis, despite it having a "Sharp" position.
- The current Terminal Shape `TSHP` has been perceived as too abstract. Probably the word "Terminal" should be avoided as this axis could potentially be used for other purposes, e.g. a family of symbols.
- Registering three different axes that somehow would overlap meaning and functions would imply repeating information and could lead to confusion.
- Registering the first two axes independently will force the third case font to use two different axes to govern a related behavior. 

Quotes from private conversations, apart from what was originally discussed in the issue [Inclusion of new custom Sharp (SHRP) axis](https://github.com/google/fonts/issues/2849):

@davelab6 
> it would be possible to nullify one axis when the other is active with a duplicate master assignment in the .designspace file's duovars. I wonder what the filesize impact would be

@tphinney 
>So in the corners (duovars) where you have Round+Sharp, put in a copy of the Regular master. The net effect is that if somebody does Round+Sharp in equal amounts, they cancel out. If somebody does say 75% Sharp and 25% Round, they get in effect 50% Sharp. Etcetera. Right?
> So, I totally get how this works technically, and it is cool and all. But I still think having the two as independent axes in the font would be super confusing to users, and unnecessarily so. They don’t really function as independent axes, and I am not seeing any benefit to having them, aside from entertaining OpenType geeks

Dave:
> this is only complicated in the case both variations exist in 1 font. This is an uncommon case

@vv-monsalve 
> Yet, probably, as all the other custom axis registered, many of them still have one single font using it
But the whole idea about the register (and the protocol we are building) is to think ahead and anticipate possible cases to avoid situations like the ones we already have for axes that failed to foreseen other cases
> This seems to me as if we were registering one "Condensed" axis plus one "Expanded" axis

Dave:
> Right, but there's a clear "width" name for that. there's no clear name for sharp..round

@thundernixon had some related reasonings on the discussion held on [Irregularity Axis](https://github.com/googlefonts/axisregistry/pull/64#issuecomment-1255380509)

**Comment by tphinney** [comment]
Just to expand on this a little more (the discussion continued at length!), I think there was fairly general agreement that it was reasonable to do this all on one axis. The reason we are not already settled on that is, the best *name* for that axis remains unclear. I think Dave, Viviana and I would all agree… if we had a great name that could be used in all these situations:
- font has full gamut of sharp (or square) to rounded
- font has just regular to rounded
- font has just regular to sharp/square/pointy

I believe fonts that only do regular to rounded will be the most common use case, but the name definitely has to _also_ work for regular-to-sharp and “full gamut” (sharp to regular to rounded) fonts—those cases will definitely also exist, and some may be quite widely used fonts.

**Comment by tphinney** [comment]
Adam Twardoch (@twardoch) points out that “terminal shape” may not communicate well to the average graphic designer or font user, who most likely doesn’t know the term “terminal” in its typographic sense.

**Comment by dberlow** [comment]
That’s easy. What hard is solving it.

**Comment by vv-monsalve** [comment]
After today's meeting, where we could review and compare the expected results for each of the above-mentioned fonts, the following are the main considerations done:

- Two fonts are actually going from square to rounded forms and don't need the negative spectrum of the range.
- One of the above fonts would use a different default value as its default begins at a different position from zero (taking it as the square extreme). Without declaring fallbacks per axis registry but per family basis (in the future), this would be possible without technical conflicts. However, @tphinney has concerns about this discrepancy in using the same axis in related fonts.
- Geologica is only going from 'flat' or square forms to pointy, spiky, or sharp forms, and the current project doesn't need the currently positive spectrum.
- Rounded fonts have a somewhat history in the industry, so they are likely to be more common or expected.
- The term "Rounded" conveys extended meanings of "kindness" and "friendliness," which sometimes are behind the creation of such variants.
- The term "Sharp(ness)" as an antonym conveys the opposite meaning of somehow "roughness" or "hardness" among others like clarity or acuity.
- @twardoch made a point built on Geologika's description, "The alternate “Sharp” styles introduces details derived from writing with a broad-nib pen." to consider using a more typographic term for this axis.
- However, taking the above reasonings around the terms and considering the reusability requirement for any new axis registered, it would be best to register this semantic pair (roundness/sharpness) as independent axes so that they can be used in multiple ways for different font projects.
- From the same reusability principle and given the non-typographic fonts (e.g. icons) would likely be increasing, we've already discussed it would probably be best to avoid the "Terminal" specific term. 

From all the above points, it seems we can close this issue here in favor of the two separated [Roundness](https://github.com/googlefonts/axisregistry/issues/59)/[Sharpness](https://github.com/googlefonts/axisregistry/issues/86) axis.

cc @chrissimpkins @davelab6

**Comment by tphinney** [comment]
So, one of the implications in the above is that this path leads us to use the same axis for two different Google projects. This is good in theory. However, these two fonts, which one might expect to be used together, will end up with different default values on the Roundness axis. I think that is… not ideal, and we should be aware of it.
cc @seasehee1
