### ISSUE TITLE
opsz: do we have too many fallbacks?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/axisregistry#45]
I'm starting to believe that we have too many fallbacks for certain axes, especially opsz.

It may be better for us to provide fallbacks only for the wght and wdth axes since these have a clear mapping to fields in the OS/2 table.

@davelab6 @evanwadams @nathan-williams

**Comment by vv-monsalve** [comment]
Closing this issue here since we have now the green dot algorithm.
@m4rc1e, please feel free to reopen it if you need to discuss anything else here
