### ISSUE TITLE
Add Extrusion Depth (EDPT) axis

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/axisregistry#60]
For Nabla, we've been recommended to use the `wght` axis for something that only vaguely relates to Weight (https://github.com/justvanrossum/nabla/issues/11)

I'd suggest to add a new axis anyway, as `wght` and "Extrusion Depth" are not mutually exclusive. 

I bet more decorative COLRv1 fonts will come with similar effects (Bungee Shadow would be a good candidate).

https://user-images.githubusercontent.com/4246121/184146939-346f6cb4-f6eb-4e6d-b176-082d02e532a4.mov

**Comment by justvanrossum** [comment]
It's not only the "Weight" axis name that hat feels a bit off for this purpose, but we also need named instances, where it would be nice to have more descriptive names for this effect. Eg. "Light" and "Black" don't quite cover it.

**Comment by justvanrossum** [comment]
Relates to #58.

**Comment by ArthurTypearture** [comment]
@justvanrossum And for a big "what if": what if we would want to add a variable weight to Nabla? These axis would clash, hence the Extrude looks like a great solution to me.

**Comment by chrissimpkins** [comment]
Thanks, Just and Arthur.  How do you see ranges and defaults working with this axis?

**Comment by justvanrossum** [comment]
The default could be anything (this significantly depends on the design).

The range could be from 0 to 1000, where the value indicates the "depth" in 1/1000 of the em square.

In a 1000 UPM font, the value could literally be the length of the red arrow in font units:

![image](https://user-images.githubusercontent.com/4246121/184303569-7cfdd3cc-01e4-4c78-b017-506646766035.png)
