### ISSUE TITLE
Add CI test that fails if no fallback is provided for a given axis textproto

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/axisregistry#67]
![Screenshot from 2022-08-18 15-27-45](https://user-images.githubusercontent.com/213676/185468302-f31fcd41-730b-4743-80a0-88daca422281.png)

Here, Element Grid has no fallback, which blocks deployment on Google Fonts servers.

**Comment by vv-monsalve** [comment]
Closing this here as it looks https://github.com/googlefonts/axisregistry/pull/68 solves it.
@felipesanches, please feel free to reopen it if necessary.
