### ISSUE TITLE
Google Axis Registry Italic Axis should be precision 0

### ISSUE THREAD

**Issue by davelab6** [googlefonts/axisregistry#73]
Today in the italic.textproto#L7 we have a precision of `-1` which allows 11 values, `0.0` through `0.5` to `1.0`. 

https://github.com/googlefonts/axisregistry/blob/636d70a3783eba649a3f5a181a1fa77afc4b2aab/Lib/axisregistry/data/italic.textproto#L7

However, we have avoided any TTFs with an `ital` axis in `fvar`, and package families with 2 TTFs, roman and italic, as if they have an `ital` axis that is binary `0..1`. 

I don't know how the current GF Catalog Front End App is coded, but the Type Tester appears to have only a switch control for the italic "axis" which is really toggling between the 2 TTFs.

Therefore we should probably tighten up the axis definition to be clear that we prefer a `slnt` axis instead of `ital` when there are intermediate steps between the Roman and Slanted+Cursive styles.

**Comment by davelab6** [comment]
https://twitter.com/_justinpenner/status/1563201894042189824?t=73EIztJfuF6LZXggNtHSnQ&s=19 is a tutorial on how to make continuous range italic axes

**Comment by RosaWagner** [comment]
Done in #82
