### ISSUE TITLE
Add Mutation [MUTA] Axis

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/axisregistry#9]
This new custom axis is included in Kablammo (a private project yet) to modify the shapes of the glyphs in a playful and sort of  "random" way.

![Morph](https://user-images.githubusercontent.com/48698976/157795775-37691bd6-9421-4840-b90d-ceb36cb3fd00.GIF)

```
tag: "MRPH"
display_name: "Morph"
min_value: 1.00
default_value: 1.00
max_value: 4.00
precision: -2
fallback {
  name: "Phase 1"
  value: 1.00
},
fallback {
  name: "Phase 2"
  value: 2.00
},
fallback {
  name: "Phase 3"
  value: 3.00
},
fallback {
  name: "Phase 4"
  value: 4.00
}
description: 
  "As the morph axis progresses, the letterforms transform"
  " into new variations, in ways specific to that typeface."
```

cc @m4rc1e @davelab6 @rsheeter

**Comment by vv-monsalve** [comment]
`Morph` would be the single axis of the project (no weight axis) thus the need for the 4 fallback positions.

On the private discussion about this axis @davelab6 said:

----

We also discussed that it will be very desirable to have the 4 named instances in the fvar table; since this is a single axis, strongly display, project, I think it worth exploring if we can establish a exception to the general fvar/stat table policy. @m4rc1e please discuss this with @vv-monsalve

**Comment by vv-monsalve** [comment]
On the private discussion about this axis @m4rc1e said:

----

Re fvar instances, no problem if you want to include all 4 styles as instances. I think for display families we should be making exceptions to our usual rule.

**Comment by vv-monsalve** [comment]
Inspecting this now I think `MORP` would be a better tag

**Comment by traviskochel** [comment]
That's ok with me

**Comment by felipesanches** [comment]
I'm risking a bike-shed debate here, but I think MRPH more closely hints (phonetically) at the word "morph"

**Comment by vv-monsalve** [comment]
> I'm risking a bike-shed debate here, but I think MRPH more closely hints (phonetically) at the word "morph"

If one already knows the actual name of the axis, then yes. But I wondered before knowing what it is and what it does, what could be more descriptive once in the font name, e.g. `Kablammo[MRPH] .ttf `or `Kablammo[MORP].ttf` 

That's why I commented it here so we can review/define it ;)
