### ISSUE TITLE
Change "Letters" in XROT and YROT description

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/axisregistry#92]
https://github.com/googlefonts/axisregistry/blob/4c8cf41fbbe6efe0181d273d661d0e7be3e82b91/Lib/axisregistry/data/x_rotation.textproto#L14

https://github.com/googlefonts/axisregistry/blob/4c8cf41fbbe6efe0181d273d661d0e7be3e82b91/Lib/axisregistry/data/y_rotation.textproto#L14

I think that we can make this more generic with a transition from "Letters" to "Shapes", or something similar?

**Comment by yanone** [comment]
Yes
